import React, { createContext, useContext, useState } from 'react';

export const languages = {
  en: { label: 'English', code: 'EN', flag: 'https://flagcdn.com/w20/gb.png' },
  es: { label: 'Español', code: 'ES', flag: 'https://flagcdn.com/w20/es.png' },
  fr: { label: 'Français', code: 'FR', flag: 'https://flagcdn.com/w20/fr.png' },
  ar: { label: 'العربية', code: 'AR', rtl: true, flag: 'https://flagcdn.com/w20/sa.png' },
  zh: { label: '中文', code: 'ZH', flag: 'https://flagcdn.com/w20/cn.png' },
  pt: { label: 'Português', code: 'PT', flag: 'https://flagcdn.com/w20/br.png' },
  hi: { label: 'हिन्दी', code: 'HI', flag: 'https://flagcdn.com/w20/in.png' },
};

export const translations = {
  en: {
    appName: 'DR Monster',
    appSubtitle: 'Diabetic Retinopathy Screening',
    footerDisclaimer: 'For screening purposes only. Consult a healthcare professional for diagnosis.',
    aboutModel: 'About Our Model',
    ourMission: 'Our Mission',
    contactUs: 'Contact Us',
    newScan: 'New Scan',
    history: 'History',
    uploadTitle: 'Upload Retina Image',
    uploadSubtitle: 'Use camera or upload from your device',
    useCamera: 'Use Camera',
    uploadFile: 'Upload File',
    uploadingImage: 'Uploading image...',
    uploadHint: 'Upload images or videos to select a clear frame for analysis',
    nameScanPlaceholder: 'Name this scan (optional)',
    analyzeButton: 'Analyze for Diabetic Retinopathy',
    analyzing: 'Analyzing...',
    scanHistory: 'Scan History',
    noScansYet: 'No scans yet',
    uploadToStart: 'Upload an image to get started',
    searchByName: 'Search by name...',
    allResults: 'All Results',
    abnormal: 'Abnormal',
    normal: 'Normal',
    pending: 'Pending',
    newest: 'Newest',
    oldest: 'Oldest',
    noScansMatch: 'No scans match the selected filter',
    renameScan: 'Rename Scan',
    enterNewName: 'Enter a new name for this scan',
    scanName: 'Scan name',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving...',
    deleteThisScan: 'Delete this scan?',
    deleteConfirm: 'This will permanently delete this scan from your history. This action cannot be undone.',
    delete: 'Delete',
    deleting: 'Deleting...',
    scanDetails: 'Scan Details',
    scannedOn: 'Scanned on',
    confidenceScore: 'Confidence Score',
    notes: 'Notes',
    addNotes: 'Add notes about this scan...',
    saveNotes: 'Save Notes',
    deleteScan: 'Delete Scan',
    confidence: 'Confidence',
    pendingAnalysis: 'Pending Analysis',
    pendingDesc: 'The analysis is still in progress. Results will be available shortly.',
    abnormalLabel: 'Abnormal',
    abnormalDesc: 'The analysis indicates potential signs of diabetic retinopathy. We recommend consulting a healthcare professional for further evaluation.',
    normalLabel: 'Normal',
    normalDesc: 'No signs of diabetic retinopathy were detected. Routine follow-up screenings are still recommended.',
    accountSettings: 'Account Settings',
    logOut: 'Log Out',
    deleteAccount: 'Delete Account',
    deleteAccountConfirm: 'Delete your account?',
    deleteAccountDesc: 'This will permanently delete your account and all associated data including scan history. This action cannot be undone.',
    joined: 'Joined',
    language: 'Language',
    selectLanguage: 'Select language',
    recording: 'Recording',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    // Disclaimer
    importantInfo: 'Important Information',
    screeningToolOnly: 'Screening Tool Only',
    screeningToolDesc: 'This tool is designed to detect potential abnormalities and help determine if a patient should seek further medical evaluation. It does not provide a medical diagnosis.',
    flashSafety: 'Flash Safety',
    flashSafetyDesc: 'Avoid prolonged flashlight exposure when capturing retina images, as extended bright light can cause discomfort or potential damage to the eye.',
    dataStorage: 'Data Storage',
    dataStorageDesc: 'Uploaded images are stored anonymously on secure servers for screening purposes. No personally identifiable information is linked to your scans.',
    iUnderstand: 'I Understand',
    cropImage: 'Crop Image',
    dragToReposition: 'Drag to reposition',
    zoom: 'Zoom',
    skip: 'Skip',
    useCrop: 'Use Crop',
    processing: 'Processing...',
    scrubVideo: 'Scrub through the video and select a clear frame',
    useThisFrame: 'Use This Frame',
    // Model Info
    trainingData: 'Training Data',
    trainingDataDesc: 'Our model was trained using 6,000 publicly available retinal images, comprising both healthy retinas and retinas with diabetic retinopathy. This diverse dataset ensures robust detection capabilities across various stages and presentations of the condition.',
    technology: 'Technology',
    technologyDesc: 'Built with PyTorch, our convolutional neural network (CNN) architecture was specifically designed for medical image analysis. After extensive training and validation, the model achieved an accuracy of 92% in detecting diabetic retinopathy.',
    privacyData: 'Privacy & Data Usage',
    privacyDataDesc: 'Your uploaded images are stored securely and anonymously for screening purposes only. We do not use your images to further train or improve the model. Your privacy and data security are our top priorities.',
    // Mission
    missionP1: 'Diabetic retinopathy screening remains out of reach for millions of people worldwide. Many communities lack the specialized equipment and trained professionals required for proper eye examinations, leaving preventable vision loss undetected.',
    missionP2: 'We built this tool to address that gap. Using only a smartphone and our mount, patients and healthcare workers anywhere in the world can access affordable, portable screening without the need for costly infrastructure or specialist referrals.',
    missionP3: 'Vision loss from diabetic retinopathy is largely preventable, yet for millions, early detection remains out of reach. Our mission is to ensure that geography and resources never determine whether someone loses their sight.',
    // Contact
    contactDesc: "Have questions, feedback, or need support? We'd love to hear from you.",
    onboardingWelcomeTitle: 'Welcome to DR Monster',
    onboardingWelcomeDesc: "This tool helps screen for potential diabetic retinopathy by analyzing retina images. Select your language below, then let's walk through how to use it.",
    onboardingCaptureTitle: 'Capture or Upload',
    onboardingCaptureDesc: 'Record a video of the retina using your device camera and select a frame, or upload an existing image or video. For best results, ensure the image is clear and well-lit.',
    onboardingHistoryTitle: 'View Your History',
    onboardingHistoryDesc: 'All your scans are saved in the History tab. You can filter by result, rename scans, and delete old ones anytime.',
    onboardingBack: 'Back',
    onboardingNext: 'Next',
    onboardingGetStarted: 'Get Started',
  },
  es: {
    appName: 'DR Monster',
    appSubtitle: 'Detección de Retinopatía Diabética',
    footerDisclaimer: 'Solo para fines de cribado. Consulte a un profesional de salud para diagnóstico.',
    aboutModel: 'Sobre el Modelo',
    ourMission: 'Nuestra Misión',
    contactUs: 'Contáctenos',
    newScan: 'Nuevo Escaneo',
    history: 'Historial',
    uploadTitle: 'Subir Imagen de Retina',
    uploadSubtitle: 'Use la cámara o suba desde su dispositivo',
    useCamera: 'Usar Cámara',
    uploadFile: 'Subir Archivo',
    uploadingImage: 'Subiendo imagen...',
    uploadHint: 'Suba imágenes o vídeos para seleccionar un fotograma para el análisis',
    nameScanPlaceholder: 'Nombre este escaneo (opcional)',
    analyzeButton: 'Analizar para Retinopatía Diabética',
    analyzing: 'Analizando...',
    scanHistory: 'Historial de Escaneos',
    noScansYet: 'Sin escaneos aún',
    uploadToStart: 'Sube una imagen para comenzar',
    searchByName: 'Buscar por nombre...',
    allResults: 'Todos los Resultados',
    abnormal: 'Anormal',
    normal: 'Normal',
    pending: 'Pendiente',
    newest: 'Más reciente',
    oldest: 'Más antiguo',
    noScansMatch: 'Ningún escaneo coincide con el filtro',
    renameScan: 'Renombrar Escaneo',
    enterNewName: 'Ingrese un nuevo nombre',
    scanName: 'Nombre del escaneo',
    cancel: 'Cancelar',
    save: 'Guardar',
    saving: 'Guardando...',
    deleteThisScan: '¿Eliminar este escaneo?',
    deleteConfirm: 'Esto eliminará permanentemente este escaneo. Esta acción no se puede deshacer.',
    delete: 'Eliminar',
    deleting: 'Eliminando...',
    scanDetails: 'Detalles del Escaneo',
    scannedOn: 'Escaneado el',
    confidenceScore: 'Puntuación de Confianza',
    notes: 'Notas',
    addNotes: 'Añadir notas sobre este escaneo...',
    saveNotes: 'Guardar Notas',
    deleteScan: 'Eliminar Escaneo',
    confidence: 'Confianza',
    pendingAnalysis: 'Análisis Pendiente',
    pendingDesc: 'El análisis aún está en progreso. Los resultados estarán disponibles pronto.',
    abnormalLabel: 'Anormal',
    abnormalDesc: 'El análisis indica posibles signos de retinopatía diabética. Recomendamos consultar a un profesional de salud.',
    normalLabel: 'Normal',
    normalDesc: 'No se detectaron signos de retinopatía diabética. Se recomiendan controles periódicos.',
    accountSettings: 'Configuración de Cuenta',
    logOut: 'Cerrar Sesión',
    deleteAccount: 'Eliminar Cuenta',
    deleteAccountConfirm: '¿Eliminar su cuenta?',
    deleteAccountDesc: 'Esto eliminará permanentemente su cuenta y todos los datos asociados. Esta acción no se puede deshacer.',
    joined: 'Se unió',
    language: 'Idioma',
    selectLanguage: 'Seleccionar idioma',
    recording: 'Grabando',
    startRecording: 'Iniciar Grabación',
    stopRecording: 'Detener Grabación',
    importantInfo: 'Información Importante',
    screeningToolOnly: 'Solo Herramienta de Cribado',
    screeningToolDesc: 'Esta herramienta está diseñada para detectar posibles anomalías y ayudar a determinar si un paciente debe buscar evaluación médica adicional. No proporciona un diagnóstico médico.',
    flashSafety: 'Seguridad del Flash',
    flashSafetyDesc: 'Evite la exposición prolongada a la linterna al capturar imágenes de retina, ya que la luz brillante prolongada puede causar molestias o daños al ojo.',
    dataStorage: 'Almacenamiento de Datos',
    dataStorageDesc: 'Las imágenes cargadas se almacenan de forma anónima en servidores seguros solo para fines de cribado. Ninguna información de identificación personal está vinculada a sus escaneos.',
    iUnderstand: 'Entiendo',
    cropImage: 'Recortar Imagen',
    dragToReposition: 'Arrastrar para reposicionar',
    zoom: 'Zoom',
    skip: 'Omitir',
    useCrop: 'Usar Recorte',
    processing: 'Procesando...',
    scrubVideo: 'Desplácese por el vídeo y seleccione un fotograma claro',
    useThisFrame: 'Usar Este Fotograma',
    trainingData: 'Datos de Entrenamiento',
    trainingDataDesc: 'Nuestro modelo fue entrenado con 6,000 imágenes retinales disponibles públicamente, que comprenden retinas sanas y retinas con retinopatía diabética.',
    technology: 'Tecnología',
    technologyDesc: 'Construido con PyTorch, nuestra arquitectura de red neuronal convolucional (CNN) fue diseñada específicamente para el análisis de imágenes médicas, logrando una precisión del 92%.',
    privacyData: 'Privacidad y Uso de Datos',
    privacyDataDesc: 'Sus imágenes cargadas se almacenan de forma segura y anónima solo para fines de cribado. No usamos sus imágenes para entrenar o mejorar el modelo.',
    missionP1: 'El cribado de retinopatía diabética sigue fuera del alcance de millones de personas en todo el mundo. Muchas comunidades carecen del equipo especializado y los profesionales capacitados necesarios para exámenes oculares adecuados.',
    missionP2: 'Construimos esta herramienta para abordar esa brecha. Usando solo un teléfono inteligente y nuestro soporte, los pacientes y trabajadores de salud en cualquier parte del mundo pueden acceder a un cribado asequible y portátil.',
    missionP3: 'La pérdida de visión por retinopatía diabética es en gran medida prevenible, sin embargo, para millones, la detección temprana sigue siendo inaccesible. Nuestra misión es garantizar que la geografía y los recursos nunca determinen si alguien pierde la vista.',
    contactDesc: '¿Tiene preguntas, comentarios o necesita soporte? Nos encantaría saber de usted.',
    onboardingWelcomeTitle: 'Bienvenido a DR Monster',
    onboardingWelcomeDesc: 'Esta herramienta ayuda a detectar posibles signos de retinopatía diabética. Seleccione su idioma a continuación.',
    onboardingCaptureTitle: 'Capturar o Subir',
    onboardingCaptureDesc: 'Grabe un vídeo de la retina usando la cámara de su dispositivo y seleccione un fotograma, o suba una imagen o vídeo existente.',
    onboardingHistoryTitle: 'Ver su Historial',
    onboardingHistoryDesc: 'Todos sus escaneos se guardan en la pestaña Historial. Puede filtrar por resultado, renombrar escaneos y eliminar los antiguos.',
    onboardingBack: 'Atrás',
    onboardingNext: 'Siguiente',
    onboardingGetStarted: 'Empezar',
  },
  fr: {
    appName: 'DR Monster',
    appSubtitle: 'Dépistage de la Rétinopathie Diabétique',
    footerDisclaimer: 'À des fins de dépistage uniquement. Consultez un professionnel de santé pour un diagnostic.',
    aboutModel: 'À propos du Modèle',
    ourMission: 'Notre Mission',
    contactUs: 'Nous Contacter',
    newScan: 'Nouveau Scan',
    history: 'Historique',
    uploadTitle: 'Télécharger une Image Rétinienne',
    uploadSubtitle: 'Utilisez la caméra ou téléchargez depuis votre appareil',
    useCamera: 'Utiliser la Caméra',
    uploadFile: 'Télécharger un Fichier',
    uploadingImage: 'Téléchargement en cours...',
    uploadHint: 'Téléchargez des images ou vidéos pour sélectionner une image nette',
    nameScanPlaceholder: 'Nommer ce scan (optionnel)',
    analyzeButton: 'Analyser pour la Rétinopathie Diabétique',
    analyzing: 'Analyse en cours...',
    scanHistory: 'Historique des Scans',
    noScansYet: 'Aucun scan pour le moment',
    uploadToStart: 'Téléchargez une image pour commencer',
    searchByName: 'Rechercher par nom...',
    allResults: 'Tous les Résultats',
    abnormal: 'Anormal',
    normal: 'Normal',
    pending: 'En attente',
    newest: 'Plus récent',
    oldest: 'Plus ancien',
    noScansMatch: 'Aucun scan ne correspond au filtre',
    renameScan: 'Renommer le Scan',
    enterNewName: 'Entrez un nouveau nom',
    scanName: 'Nom du scan',
    cancel: 'Annuler',
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    deleteThisScan: 'Supprimer ce scan ?',
    deleteConfirm: 'Cela supprimera définitivement ce scan. Cette action est irréversible.',
    delete: 'Supprimer',
    deleting: 'Suppression...',
    scanDetails: 'Détails du Scan',
    scannedOn: 'Scanné le',
    confidenceScore: 'Score de Confiance',
    notes: 'Notes',
    addNotes: 'Ajouter des notes sur ce scan...',
    saveNotes: 'Enregistrer les Notes',
    deleteScan: 'Supprimer le Scan',
    confidence: 'Confiance',
    pendingAnalysis: 'Analyse en Attente',
    pendingDesc: "L'analyse est encore en cours. Les résultats seront disponibles bientôt.",
    abnormalLabel: 'Anormal',
    abnormalDesc: "L'analyse indique des signes potentiels de rétinopathie diabétique. Nous recommandons de consulter un professionnel de santé.",
    normalLabel: 'Normal',
    normalDesc: "Aucun signe de rétinopathie diabétique n'a été détecté. Des examens de suivi réguliers sont toujours recommandés.",
    accountSettings: 'Paramètres du Compte',
    logOut: 'Se Déconnecter',
    deleteAccount: 'Supprimer le Compte',
    deleteAccountConfirm: 'Supprimer votre compte ?',
    deleteAccountDesc: 'Cela supprimera définitivement votre compte et toutes les données associées. Cette action est irréversible.',
    joined: 'Inscrit le',
    language: 'Langue',
    selectLanguage: 'Choisir la langue',
    recording: 'Enregistrement',
    startRecording: "Démarrer l'Enregistrement",
    stopRecording: "Arrêter l'Enregistrement",
    importantInfo: 'Informations Importantes',
    screeningToolOnly: 'Outil de Dépistage Uniquement',
    screeningToolDesc: "Cet outil est conçu pour détecter des anomalies potentielles et aider à déterminer si un patient doit consulter un médecin. Il ne fournit pas de diagnostic médical.",
    flashSafety: 'Sécurité du Flash',
    flashSafetyDesc: "Évitez une exposition prolongée à la lampe de poche lors de la capture d'images rétiniennes, car une lumière vive prolongée peut causer de l'inconfort ou des dommages à l'œil.",
    dataStorage: 'Stockage des Données',
    dataStorageDesc: "Les images téléchargées sont stockées anonymement sur des serveurs sécurisés à des fins de dépistage uniquement. Aucune information personnelle n'est liée à vos scans.",
    iUnderstand: 'Je Comprends',
    cropImage: "Recadrer l'Image",
    dragToReposition: 'Glisser pour repositionner',
    zoom: 'Zoom',
    skip: 'Ignorer',
    useCrop: 'Utiliser le Recadrage',
    processing: 'Traitement...',
    scrubVideo: 'Parcourez la vidéo et sélectionnez une image nette',
    useThisFrame: 'Utiliser Cette Image',
    trainingData: "Données d'Entraînement",
    trainingDataDesc: "Notre modèle a été entraîné avec 6 000 images rétiniennes disponibles publiquement, comprenant des rétines saines et des rétines atteintes de rétinopathie diabétique, atteignant une précision de 92%.",
    technology: 'Technologie',
    technologyDesc: "Construit avec PyTorch, notre architecture de réseau neuronal convolutif (CNN) a été spécialement conçue pour l'analyse d'images médicales.",
    privacyData: 'Confidentialité et Utilisation des Données',
    privacyDataDesc: "Vos images téléchargées sont stockées de manière sécurisée et anonyme à des fins de dépistage uniquement. Nous n'utilisons pas vos images pour entraîner ou améliorer le modèle.",
    missionP1: "Le dépistage de la rétinopathie diabétique reste hors de portée pour des millions de personnes dans le monde. De nombreuses communautés manquent d'équipements spécialisés et de professionnels formés.",
    missionP2: "Nous avons créé cet outil pour combler cette lacune. En utilisant uniquement un smartphone et notre support, les patients et les travailleurs de santé partout dans le monde peuvent accéder à un dépistage abordable et portable.",
    missionP3: "La perte de vision due à la rétinopathie diabétique est en grande partie évitable, pourtant pour des millions de personnes, la détection précoce reste hors de portée. Notre mission est de garantir que la géographie et les ressources ne déterminent jamais si quelqu'un perd la vue.",
    contactDesc: "Des questions, des commentaires ou besoin d'aide ? Nous aimerions avoir de vos nouvelles.",
    onboardingWelcomeTitle: 'Bienvenue sur DR Monster',
    onboardingWelcomeDesc: 'Cet outil aide à dépister la rétinopathie diabétique. Sélectionnez votre langue ci-dessous.',
    onboardingCaptureTitle: 'Capturer ou Télécharger',
    onboardingCaptureDesc: 'Enregistrez une vidéo de la rétine avec votre caméra et sélectionnez une image, ou téléchargez une image ou vidéo existante.',
    onboardingHistoryTitle: 'Voir votre Historique',
    onboardingHistoryDesc: "Tous vos scans sont enregistrés dans l'onglet Historique. Vous pouvez filtrer par résultat, renommer et supprimer des scans.",
    onboardingBack: 'Retour',
    onboardingNext: 'Suivant',
    onboardingGetStarted: 'Commencer',
  },
  ar: {
    appName: 'DR Monster',
    appSubtitle: 'فحص اعتلال الشبكية السكري',
    footerDisclaimer: 'لأغراض الفحص فقط. استشر متخصصاً في الرعاية الصحية للتشخيص.',
    aboutModel: 'عن النموذج',
    ourMission: 'مهمتنا',
    contactUs: 'اتصل بنا',
    newScan: 'فحص جديد',
    history: 'السجل',
    uploadTitle: 'رفع صورة الشبكية',
    uploadSubtitle: 'استخدم الكاميرا أو ارفع من جهازك',
    useCamera: 'استخدام الكاميرا',
    uploadFile: 'رفع ملف',
    uploadingImage: 'جارٍ رفع الصورة...',
    uploadHint: 'ارفع صوراً أو مقاطع فيديو لاختيار إطار واضح للتحليل',
    nameScanPlaceholder: 'اسم الفحص (اختياري)',
    analyzeButton: 'تحليل اعتلال الشبكية السكري',
    analyzing: 'جارٍ التحليل...',
    scanHistory: 'سجل الفحوصات',
    noScansYet: 'لا توجد فحوصات بعد',
    uploadToStart: 'ارفع صورة للبدء',
    searchByName: 'البحث بالاسم...',
    allResults: 'جميع النتائج',
    abnormal: 'غير طبيعي',
    normal: 'طبيعي',
    pending: 'قيد الانتظار',
    newest: 'الأحدث',
    oldest: 'الأقدم',
    noScansMatch: 'لا توجد فحوصات تطابق الفلتر',
    renameScan: 'إعادة تسمية الفحص',
    enterNewName: 'أدخل اسماً جديداً',
    scanName: 'اسم الفحص',
    cancel: 'إلغاء',
    save: 'حفظ',
    saving: 'جارٍ الحفظ...',
    deleteThisScan: 'حذف هذا الفحص؟',
    deleteConfirm: 'سيتم حذف هذا الفحص نهائياً. لا يمكن التراجع عن هذا الإجراء.',
    delete: 'حذف',
    deleting: 'جارٍ الحذف...',
    scanDetails: 'تفاصيل الفحص',
    scannedOn: 'تم الفحص في',
    confidenceScore: 'درجة الثقة',
    notes: 'ملاحظات',
    addNotes: 'أضف ملاحظات حول هذا الفحص...',
    saveNotes: 'حفظ الملاحظات',
    deleteScan: 'حذف الفحص',
    confidence: 'الثقة',
    pendingAnalysis: 'التحليل قيد الانتظار',
    pendingDesc: 'التحليل لا يزال جارياً. ستتوفر النتائج قريباً.',
    abnormalLabel: 'غير طبيعي',
    abnormalDesc: 'يشير التحليل إلى علامات محتملة لاعتلال الشبكية السكري. نوصي باستشارة متخصص في الرعاية الصحية.',
    normalLabel: 'طبيعي',
    normalDesc: 'لم يتم اكتشاف أي علامات لاعتلال الشبكية السكري. لا تزال الفحوصات الدورية موصى بها.',
    accountSettings: 'إعدادات الحساب',
    logOut: 'تسجيل الخروج',
    deleteAccount: 'حذف الحساب',
    deleteAccountConfirm: 'حذف حسابك؟',
    deleteAccountDesc: 'سيؤدي هذا إلى حذف حسابك وجميع البيانات المرتبطة به نهائياً. لا يمكن التراجع عن هذا الإجراء.',
    joined: 'انضم في',
    language: 'اللغة',
    selectLanguage: 'اختر اللغة',
    recording: 'تسجيل',
    startRecording: 'بدء التسجيل',
    stopRecording: 'إيقاف التسجيل',
    importantInfo: 'معلومات مهمة',
    screeningToolOnly: 'أداة فحص فقط',
    screeningToolDesc: 'تم تصميم هذه الأداة للكشف عن الشذوذات المحتملة والمساعدة في تحديد ما إذا كان المريض يحتاج إلى تقييم طبي إضافي. لا توفر تشخيصاً طبياً.',
    flashSafety: 'سلامة الفلاش',
    flashSafetyDesc: 'تجنب التعرض المطول للضوء عند التقاط صور الشبكية، حيث يمكن أن يسبب الضوء الساطع الممتد إزعاجاً أو ضرراً محتملاً للعين.',
    dataStorage: 'تخزين البيانات',
    dataStorageDesc: 'يتم تخزين الصور المرفوعة بشكل مجهول على خوادم آمنة لأغراض الفحص فقط. لا يتم ربط أي معلومات تعريفية شخصية بفحوصاتك.',
    iUnderstand: 'أفهم',
    cropImage: 'قص الصورة',
    dragToReposition: 'اسحب لإعادة التموضع',
    zoom: 'تكبير',
    skip: 'تخطي',
    useCrop: 'استخدام القص',
    processing: 'جارٍ المعالجة...',
    scrubVideo: 'تصفح الفيديو واختر إطاراً واضحاً',
    useThisFrame: 'استخدام هذا الإطار',
    trainingData: 'بيانات التدريب',
    trainingDataDesc: 'تم تدريب نموذجنا باستخدام 6000 صورة شبكية متاحة للعموم، تشمل شبكيات سليمة وشبكيات مصابة باعتلال الشبكية السكري، محققاً دقة 92%.',
    technology: 'التكنولوجيا',
    technologyDesc: 'مبني باستخدام PyTorch، تم تصميم بنية شبكتنا العصبية التلافيفية (CNN) خصيصاً لتحليل الصور الطبية.',
    privacyData: 'الخصوصية واستخدام البيانات',
    privacyDataDesc: 'يتم تخزين صورك المرفوعة بأمان وبشكل مجهول لأغراض الفحص فقط. نحن لا نستخدم صورك لتدريب أو تحسين النموذج.',
    missionP1: 'يظل فحص اعتلال الشبكية السكري بعيد المنال لملايين الأشخاص حول العالم. تفتقر العديد من المجتمعات إلى المعدات المتخصصة والمهنيين المدربين.',
    missionP2: 'بنينا هذه الأداة لمعالجة تلك الفجوة. باستخدام هاتف ذكي فقط، يمكن للمرضى والعاملين في الرعاية الصحية في أي مكان في العالم الوصول إلى فحص ميسور التكلفة.',
    missionP3: 'فقدان البصر الناجم عن اعتلال الشبكية السكري يمكن منعه إلى حد بعيد، ومع ذلك لا يزال الكشف المبكر بعيد المنال للملايين. مهمتنا هي ضمان ألا تحدد الجغرافيا والموارد ما إذا كان شخص ما يفقد بصره.',
    contactDesc: 'هل لديك أسئلة أو ملاحظات أو تحتاج إلى دعم؟ يسعدنا أن نسمع منك.',
    onboardingWelcomeTitle: 'مرحباً في DR Monster',
    onboardingWelcomeDesc: 'تساعد هذه الأداة على فحص اعتلال الشبكية السكري. اختر لغتك أدناه.',
    onboardingCaptureTitle: 'التقاط أو رفع',
    onboardingCaptureDesc: 'سجّل فيديو للشبكية باستخدام كاميرا جهازك واختر إطاراً، أو ارفع صورة أو فيديو موجوداً.',
    onboardingHistoryTitle: 'عرض السجل',
    onboardingHistoryDesc: 'تُحفظ جميع فحوصاتك في تبويب السجل. يمكنك التصفية، وإعادة التسمية، وحذف الفحوصات القديمة.',
    onboardingBack: 'رجوع',
    onboardingNext: 'التالي',
    onboardingGetStarted: 'ابدأ',
  },
  zh: {
    appName: 'DR Monster',
    appSubtitle: '糖尿病视网膜病变筛查',
    footerDisclaimer: '仅用于筛查目的。请咨询医疗专业人员进行诊断。',
    aboutModel: '关于模型',
    ourMission: '我们的使命',
    contactUs: '联系我们',
    newScan: '新扫描',
    history: '历史记录',
    uploadTitle: '上传视网膜图像',
    uploadSubtitle: '使用相机或从设备上传',
    useCamera: '使用相机',
    uploadFile: '上传文件',
    uploadingImage: '正在上传图像...',
    uploadHint: '上传图像或视频以选择清晰帧进行分析',
    nameScanPlaceholder: '为此次扫描命名（可选）',
    analyzeButton: '分析糖尿病视网膜病变',
    analyzing: '分析中...',
    scanHistory: '扫描历史',
    noScansYet: '暂无扫描记录',
    uploadToStart: '上传图像开始',
    searchByName: '按名称搜索...',
    allResults: '所有结果',
    abnormal: '异常',
    normal: '正常',
    pending: '待处理',
    newest: '最新',
    oldest: '最旧',
    noScansMatch: '没有符合筛选条件的扫描',
    renameScan: '重命名扫描',
    enterNewName: '输入新名称',
    scanName: '扫描名称',
    cancel: '取消',
    save: '保存',
    saving: '保存中...',
    deleteThisScan: '删除此扫描？',
    deleteConfirm: '这将永久删除此扫描记录。此操作无法撤销。',
    delete: '删除',
    deleting: '删除中...',
    scanDetails: '扫描详情',
    scannedOn: '扫描于',
    confidenceScore: '置信度分数',
    notes: '备注',
    addNotes: '添加此次扫描的备注...',
    saveNotes: '保存备注',
    deleteScan: '删除扫描',
    confidence: '置信度',
    pendingAnalysis: '分析待处理',
    pendingDesc: '分析仍在进行中。结果将很快可用。',
    abnormalLabel: '异常',
    abnormalDesc: '分析显示可能存在糖尿病视网膜病变迹象。建议咨询医疗专业人员。',
    normalLabel: '正常',
    normalDesc: '未检测到糖尿病视网膜病变迹象。仍建议定期随访筛查。',
    accountSettings: '账户设置',
    logOut: '退出登录',
    deleteAccount: '删除账户',
    deleteAccountConfirm: '删除您的账户？',
    deleteAccountDesc: '这将永久删除您的账户和所有相关数据，包括扫描历史记录。此操作无法撤销。',
    joined: '加入于',
    language: '语言',
    selectLanguage: '选择语言',
    recording: '录制中',
    startRecording: '开始录制',
    stopRecording: '停止录制',
    importantInfo: '重要信息',
    screeningToolOnly: '仅供筛查使用',
    screeningToolDesc: '该工具旨在检测潜在异常，帮助确定患者是否需要进一步医疗评估。它不提供医学诊断。',
    flashSafety: '闪光灯安全',
    flashSafetyDesc: '拍摄视网膜图像时避免长时间手电筒照射，因为长时间强光可能导致不适或潜在的眼睛损伤。',
    dataStorage: '数据存储',
    dataStorageDesc: '上传的图像以匿名方式存储在安全服务器上，仅用于筛查目的。没有任何个人身份信息与您的扫描相关联。',
    iUnderstand: '我明白了',
    cropImage: '裁剪图像',
    dragToReposition: '拖动以重新定位',
    zoom: '缩放',
    skip: '跳过',
    useCrop: '使用裁剪',
    processing: '处理中...',
    scrubVideo: '滚动视频并选择清晰帧',
    useThisFrame: '使用此帧',
    trainingData: '训练数据',
    trainingDataDesc: '我们的模型使用6000张公开可用的视网膜图像进行训练，包括健康视网膜和患有糖尿病视网膜病变的视网膜，达到92%的准确率。',
    technology: '技术',
    technologyDesc: '基于PyTorch构建，我们的卷积神经网络(CNN)架构专为医学图像分析而设计。',
    privacyData: '隐私与数据使用',
    privacyDataDesc: '您上传的图像仅用于筛查目的，以安全匿名的方式存储。我们不会使用您的图像来进一步训练或改进模型。',
    missionP1: '糖尿病视网膜病变筛查对全球数百万人来说仍然遥不可及。许多社区缺乏适当眼科检查所需的专业设备和训练有素的专业人员。',
    missionP2: '我们开发了这个工具来解决这一差距。仅使用智能手机，世界各地的患者和医疗工作者都可以获得负担得起的便携式筛查。',
    missionP3: '糖尿病视网膜病变导致的视力丧失在很大程度上是可以预防的，然而对数百万人来说，早期检测仍然遥不可及。我们的使命是确保地理位置和资源永远不会决定某人是否失去视力。',
    contactDesc: '有问题、反馈或需要支持？我们很乐意听取您的意见。',
    onboardingWelcomeTitle: '欢迎使用 DR Monster',
    onboardingWelcomeDesc: '此工具帮助筛查糖尿病视网膜病变。请在下方选择您的语言。',
    onboardingCaptureTitle: '拍摄或上传',
    onboardingCaptureDesc: '使用设备摄像头录制视网膜视频并选择帧，或上传现有图像或视频。',
    onboardingHistoryTitle: '查看历史记录',
    onboardingHistoryDesc: '所有扫描都保存在历史记录选项卡中。您可以按结果筛选、重命名和删除旧记录。',
    onboardingBack: '返回',
    onboardingNext: '下一步',
    onboardingGetStarted: '开始',
  },
  pt: {
    appName: 'DR Monster',
    appSubtitle: 'Triagem de Retinopatia Diabética',
    footerDisclaimer: 'Apenas para fins de triagem. Consulte um profissional de saúde para diagnóstico.',
    aboutModel: 'Sobre o Modelo',
    ourMission: 'Nossa Missão',
    contactUs: 'Fale Conosco',
    newScan: 'Nova Varredura',
    history: 'Histórico',
    uploadTitle: 'Enviar Imagem da Retina',
    uploadSubtitle: 'Use a câmera ou envie do seu dispositivo',
    useCamera: 'Usar Câmera',
    uploadFile: 'Enviar Arquivo',
    uploadingImage: 'Enviando imagem...',
    uploadHint: 'Envie imagens ou vídeos para selecionar um quadro claro para análise',
    nameScanPlaceholder: 'Nomear esta varredura (opcional)',
    analyzeButton: 'Analisar para Retinopatia Diabética',
    analyzing: 'Analisando...',
    scanHistory: 'Histórico de Varreduras',
    noScansYet: 'Nenhuma varredura ainda',
    uploadToStart: 'Envie uma imagem para começar',
    searchByName: 'Pesquisar por nome...',
    allResults: 'Todos os Resultados',
    abnormal: 'Anormal',
    normal: 'Normal',
    pending: 'Pendente',
    newest: 'Mais recente',
    oldest: 'Mais antigo',
    noScansMatch: 'Nenhuma varredura corresponde ao filtro',
    renameScan: 'Renomear Varredura',
    enterNewName: 'Digite um novo nome',
    scanName: 'Nome da varredura',
    cancel: 'Cancelar',
    save: 'Salvar',
    saving: 'Salvando...',
    deleteThisScan: 'Excluir esta varredura?',
    deleteConfirm: 'Isso excluirá permanentemente esta varredura. Esta ação não pode ser desfeita.',
    delete: 'Excluir',
    deleting: 'Excluindo...',
    scanDetails: 'Detalhes da Varredura',
    scannedOn: 'Varrido em',
    confidenceScore: 'Pontuação de Confiança',
    notes: 'Notas',
    addNotes: 'Adicionar notas sobre esta varredura...',
    saveNotes: 'Salvar Notas',
    deleteScan: 'Excluir Varredura',
    confidence: 'Confiança',
    pendingAnalysis: 'Análise Pendente',
    pendingDesc: 'A análise ainda está em andamento. Os resultados estarão disponíveis em breve.',
    abnormalLabel: 'Anormal',
    abnormalDesc: 'A análise indica possíveis sinais de retinopatia diabética. Recomendamos consultar um profissional de saúde.',
    normalLabel: 'Normal',
    normalDesc: 'Nenhum sinal de retinopatia diabética foi detectado. Exames de acompanhamento regulares ainda são recomendados.',
    accountSettings: 'Configurações da Conta',
    logOut: 'Sair',
    deleteAccount: 'Excluir Conta',
    deleteAccountConfirm: 'Excluir sua conta?',
    deleteAccountDesc: 'Isso excluirá permanentemente sua conta e todos os dados associados. Esta ação não pode ser desfeita.',
    joined: 'Entrou em',
    language: 'Idioma',
    selectLanguage: 'Selecionar idioma',
    recording: 'Gravando',
    startRecording: 'Iniciar Gravação',
    stopRecording: 'Parar Gravação',
    importantInfo: 'Informações Importantes',
    screeningToolOnly: 'Apenas Ferramenta de Triagem',
    screeningToolDesc: 'Esta ferramenta foi projetada para detectar possíveis anomalias e ajudar a determinar se um paciente deve buscar avaliação médica adicional. Ela não fornece diagnóstico médico.',
    flashSafety: 'Segurança do Flash',
    flashSafetyDesc: 'Evite exposição prolongada à lanterna ao capturar imagens da retina, pois luz brilhante prolongada pode causar desconforto ou danos potenciais ao olho.',
    dataStorage: 'Armazenamento de Dados',
    dataStorageDesc: 'As imagens enviadas são armazenadas anonimamente em servidores seguros apenas para fins de triagem. Nenhuma informação pessoal identificável está vinculada às suas varreduras.',
    iUnderstand: 'Eu Entendo',
    cropImage: 'Recortar Imagem',
    dragToReposition: 'Arraste para reposicionar',
    zoom: 'Zoom',
    skip: 'Pular',
    useCrop: 'Usar Recorte',
    processing: 'Processando...',
    scrubVideo: 'Navegue pelo vídeo e selecione um quadro claro',
    useThisFrame: 'Usar Este Quadro',
    trainingData: 'Dados de Treinamento',
    trainingDataDesc: 'Nosso modelo foi treinado usando 6.000 imagens retinais publicamente disponíveis, compreendendo retinas saudáveis e retinas com retinopatia diabética, alcançando 92% de precisão.',
    technology: 'Tecnologia',
    technologyDesc: 'Construído com PyTorch, nossa arquitetura de rede neural convolucional (CNN) foi projetada especificamente para análise de imagens médicas.',
    privacyData: 'Privacidade e Uso de Dados',
    privacyDataDesc: 'Suas imagens enviadas são armazenadas de forma segura e anônima apenas para fins de triagem. Não usamos suas imagens para treinar ou melhorar o modelo.',
    missionP1: 'A triagem de retinopatia diabética continua fora do alcance de milhões de pessoas em todo o mundo. Muitas comunidades carecem de equipamentos especializados e profissionais treinados.',
    missionP2: 'Criamos esta ferramenta para preencher essa lacuna. Usando apenas um smartphone, pacientes e profissionais de saúde em qualquer lugar do mundo podem acessar triagem acessível e portátil.',
    missionP3: 'A perda de visão por retinopatia diabética é em grande parte evitável, mas para milhões, a detecção precoce continua fora do alcance. Nossa missão é garantir que a geografia e os recursos nunca determinem se alguém perde a visão.',
    contactDesc: 'Tem perguntas, feedback ou precisa de suporte? Adoraríamos ouvir de você.',
    onboardingWelcomeTitle: 'Bem-vindo ao DR Monster',
    onboardingWelcomeDesc: 'Esta ferramenta ajuda a detectar retinopatia diabética. Selecione seu idioma abaixo.',
    onboardingCaptureTitle: 'Capturar ou Enviar',
    onboardingCaptureDesc: 'Grave um vídeo da retina com a câmera do seu dispositivo e selecione um quadro, ou envie uma imagem ou vídeo existente.',
    onboardingHistoryTitle: 'Ver seu Histórico',
    onboardingHistoryDesc: 'Todas as suas varreduras são salvas na aba Histórico. Você pode filtrar, renomear e excluir registros antigos.',
    onboardingBack: 'Voltar',
    onboardingNext: 'Próximo',
    onboardingGetStarted: 'Começar',
  },
  hi: {
    appName: 'DR Monster',
    appSubtitle: 'डायबिटिक रेटिनोपैथी स्क्रीनिंग',
    footerDisclaimer: 'केवल स्क्रीनिंग उद्देश्यों के लिए। निदान के लिए स्वास्थ्य पेशेवर से परामर्श करें।',
    aboutModel: 'हमारे मॉडल के बारे में',
    ourMission: 'हमारा मिशन',
    contactUs: 'संपर्क करें',
    newScan: 'नया स्कैन',
    history: 'इतिहास',
    uploadTitle: 'रेटिना छवि अपलोड करें',
    uploadSubtitle: 'कैमरा उपयोग करें या अपने डिवाइस से अपलोड करें',
    useCamera: 'कैमरा उपयोग करें',
    uploadFile: 'फ़ाइल अपलोड करें',
    uploadingImage: 'छवि अपलोड हो रही है...',
    uploadHint: 'विश्लेषण के लिए स्पष्ट फ्रेम चुनने के लिए चित्र या वीडियो अपलोड करें',
    nameScanPlaceholder: 'इस स्कैन को नाम दें (वैकल्पिक)',
    analyzeButton: 'डायबिटिक रेटिनोपैथी के लिए विश्लेषण करें',
    analyzing: 'विश्लेषण हो रहा है...',
    scanHistory: 'स्कैन इतिहास',
    noScansYet: 'अभी तक कोई स्कैन नहीं',
    uploadToStart: 'शुरू करने के लिए एक छवि अपलोड करें',
    searchByName: 'नाम से खोजें...',
    allResults: 'सभी परिणाम',
    abnormal: 'असामान्य',
    normal: 'सामान्य',
    pending: 'लंबित',
    newest: 'नवीनतम',
    oldest: 'सबसे पुराना',
    noScansMatch: 'कोई स्कैन फ़िल्टर से मेल नहीं खाता',
    renameScan: 'स्कैन का नाम बदलें',
    enterNewName: 'नया नाम दर्ज करें',
    scanName: 'स्कैन का नाम',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    saving: 'सहेजा जा रहा है...',
    deleteThisScan: 'यह स्कैन हटाएं?',
    deleteConfirm: 'यह इस स्कैन को स्थायी रूप से हटा देगा। यह क्रिया पूर्ववत नहीं की जा सकती।',
    delete: 'हटाएं',
    deleting: 'हटाया जा रहा है...',
    scanDetails: 'स्कैन विवरण',
    scannedOn: 'स्कैन किया गया',
    confidenceScore: 'विश्वास स्कोर',
    notes: 'नोट्स',
    addNotes: 'इस स्कैन के बारे में नोट्स जोड़ें...',
    saveNotes: 'नोट्स सहेजें',
    deleteScan: 'स्कैन हटाएं',
    confidence: 'विश्वास',
    pendingAnalysis: 'विश्लेषण लंबित',
    pendingDesc: 'विश्लेषण अभी भी प्रगति में है। परिणाम जल्द उपलब्ध होंगे।',
    abnormalLabel: 'असामान्य',
    abnormalDesc: 'विश्लेषण डायबिटिक रेटिनोपैथी के संभावित संकेत दर्शाता है। स्वास्थ्य पेशेवर से परामर्श करें।',
    normalLabel: 'सामान्य',
    normalDesc: 'डायबिटिक रेटिनोपैथी के कोई संकेत नहीं मिले। नियमित फॉलो-अप स्क्रीनिंग अभी भी अनुशंसित है।',
    accountSettings: 'खाता सेटिंग',
    logOut: 'लॉग आउट',
    deleteAccount: 'खाता हटाएं',
    deleteAccountConfirm: 'अपना खाता हटाएं?',
    deleteAccountDesc: 'यह आपके खाते और सभी संबंधित डेटा को स्थायी रूप से हटा देगा। यह क्रिया पूर्ववत नहीं की जा सकती।',
    joined: 'शामिल हुए',
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    recording: 'रिकॉर्डिंग',
    startRecording: 'रिकॉर्डिंग शुरू करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    importantInfo: 'महत्वपूर्ण जानकारी',
    screeningToolOnly: 'केवल स्क्रीनिंग टूल',
    screeningToolDesc: 'यह टूल संभावित असामान्यताओं का पता लगाने और यह निर्धारित करने में मदद करने के लिए बनाया गया है कि क्या रोगी को आगे चिकित्सा मूल्यांकन की आवश्यकता है। यह चिकित्सा निदान नहीं देता।',
    flashSafety: 'फ्लैश सुरक्षा',
    flashSafetyDesc: 'रेटिना छवियां कैप्चर करते समय लंबे समय तक फ्लैशलाइट के संपर्क से बचें, क्योंकि लंबे समय तक तेज रोशनी आंख को असुविधा या संभावित नुकसान पहुंचा सकती है।',
    dataStorage: 'डेटा संग्रहण',
    dataStorageDesc: 'अपलोड की गई छवियां केवल स्क्रीनिंग उद्देश्यों के लिए सुरक्षित सर्वर पर अनाम रूप से संग्रहीत की जाती हैं। कोई व्यक्तिगत पहचान योग्य जानकारी आपके स्कैन से जुड़ी नहीं है।',
    iUnderstand: 'मैं समझता/समझती हूं',
    cropImage: 'छवि क्रॉप करें',
    dragToReposition: 'पुनः स्थिति के लिए खींचें',
    zoom: 'ज़ूम',
    skip: 'छोड़ें',
    useCrop: 'क्रॉप का उपयोग करें',
    processing: 'प्रसंस्करण हो रहा है...',
    scrubVideo: 'वीडियो में स्क्रॉल करें और स्पष्ट फ्रेम चुनें',
    useThisFrame: 'इस फ्रेम का उपयोग करें',
    trainingData: 'प्रशिक्षण डेटा',
    trainingDataDesc: 'हमारे मॉडल को 6,000 सार्वजनिक रूप से उपलब्ध रेटिनल छवियों का उपयोग करके प्रशिक्षित किया गया था, जिसमें स्वस्थ रेटिना और डायबिटिक रेटिनोपैथी वाले रेटिना शामिल हैं, जिससे 92% सटीकता हासिल हुई।',
    technology: 'प्रौद्योगिकी',
    technologyDesc: 'PyTorch के साथ निर्मित, हमारी कनवोल्यूशनल न्यूरल नेटवर्क (CNN) आर्किटेक्चर विशेष रूप से चिकित्सा छवि विश्लेषण के लिए डिज़ाइन की गई थी।',
    privacyData: 'गोपनीयता और डेटा उपयोग',
    privacyDataDesc: 'आपकी अपलोड की गई छवियां केवल स्क्रीनिंग उद्देश्यों के लिए सुरक्षित और अनाम रूप से संग्रहीत की जाती हैं। हम आपकी छवियों का उपयोग मॉडल को प्रशिक्षित या बेहतर बनाने के लिए नहीं करते।',
    missionP1: 'डायबिटिक रेटिनोपैथी स्क्रीनिंग दुनिया भर में लाखों लोगों की पहुंच से बाहर बनी हुई है। कई समुदायों में उचित आंख परीक्षण के लिए विशेष उपकरण और प्रशिक्षित पेशेवरों की कमी है।',
    missionP2: 'हमने उस अंतर को दूर करने के लिए यह टूल बनाया। केवल एक स्मार्टफोन का उपयोग करके, दुनिया भर के मरीज और स्वास्थ्य कर्मचारी किफायती, पोर्टेबल स्क्रीनिंग तक पहुंच सकते हैं।',
    missionP3: 'डायबिटिक रेटिनोपैथी से दृष्टि हानि काफी हद तक रोकी जा सकती है, फिर भी लाखों लोगों के लिए शुरुआती पहचान पहुंच से बाहर है। हमारा मिशन यह सुनिश्चित करना है कि भूगोल और संसाधन कभी यह न निर्धारित करें कि कोई अपनी दृष्टि खोता है।',
    contactDesc: 'प्रश्न, प्रतिक्रिया, या सहायता चाहिए? हम आपसे सुनना पसंद करेंगे।',
    onboardingWelcomeTitle: 'DR Monster में आपका स्वागत है',
    onboardingWelcomeDesc: 'यह टूल डायबिटिक रेटिनोपैथी की जांच में मदद करता है। नीचे अपनी भाषा चुनें।',
    onboardingCaptureTitle: 'कैप्चर करें या अपलोड करें',
    onboardingCaptureDesc: 'अपने डिवाइस कैमरा से रेटिना वीडियो रिकॉर्ड करें और एक फ्रेम चुनें, या मौजूदा छवि या वीडियो अपलोड करें।',
    onboardingHistoryTitle: 'अपना इतिहास देखें',
    onboardingHistoryDesc: 'आपके सभी स्कैन इतिहास टैब में सहेजे जाते हैं। आप परिणाम के अनुसार फ़िल्टर कर सकते हैं, स्कैन का नाम बदल सकते हैं और पुराने हटा सकते हैं।',
    onboardingBack: 'वापस',
    onboardingNext: 'अगला',
    onboardingGetStarted: 'शुरू करें',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('appLanguage') || 'en');

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('appLanguage', newLang);
  };

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  const isRtl = languages[lang]?.rtl || false;

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}